import 'package:flutter/material.dart';

Color checkColor(String name) {
  switch (name){
    case 'transparent':
      return Colors.transparent;
    case 'black':
      return Colors.black;
    case 'black87':
      return Colors.black87;
    case 'black54':
      return Colors.black54;
    case 'black45':
      return Colors.black45;
    case 'black38':
      return Colors.black38;
    case 'black26':
      return Colors.black26;
    case 'white':
      return Colors.white;
    case 'white70':
      return Colors.white70;
    case 'white60':
      return Colors.white60;
    case 'white54':
      return Colors.white54;
    case 'white38':
      return Colors.white38;
    case 'white30':
      return Colors.white30;
    case 'white24':
      return Colors.white24;
    case 'white12':
      return Colors.white12;
    case 'red':
      return Colors.red;
    case 'redAccent':
      return Colors.redAccent;
    case 'pink':
      return Colors.pink;
    case 'pinkAccent':
      return Colors.pinkAccent;
    case 'purple':
      return Colors.purple;
    case 'purpleAccent':
      return Colors.purpleAccent;
    case 'deepPurple':
      return Colors.deepPurple;
    case 'deepPurpleAccent':
      return Colors.deepPurpleAccent;
    case 'indigo':
      return Colors.indigo;
    case 'indigoAccent':
      return Colors.indigoAccent;
    case 'blue':
      return Colors.blue;
    case 'blueAccent':
      return Colors.blueAccent;
    case 'lightBlue':
      return Colors.lightBlue;
    case 'lightBlueAccent':
      return Colors.lightBlueAccent;
    case 'cyan':
      return Colors.cyan;
    case 'cyanAccent':
      return Colors.cyanAccent;
    case 'teal':
      return Colors.teal;
    case 'tealAccent':
      return Colors.tealAccent;
    case 'green':
      return Colors.green;
    case 'greenAccent':
      return Colors.greenAccent;
    case 'lightGreen':
      return Colors.lightGreen;
    case 'lightGreenAccent':
      return Colors.lightGreenAccent;
    case 'lime':
      return Colors.lime;
    case 'limeAccent':
      return Colors.limeAccent;
    case 'yellow':
      return Colors.yellow;
    case 'yellowAccent':
      return Colors.yellowAccent;
    case 'amber':
      return Colors.amber;
    case 'amberAccent':
      return Colors.amberAccent;
    case 'orange':
      return Colors.orange;
    case 'orangeAccent':
      return Colors.orangeAccent;
    case 'deepOrange':
      return Colors.deepOrange;
    case 'deepOrangeAccent':
      return Colors.deepOrangeAccent;
    case 'brown':
      return Colors.brown;
    case 'grey':
      return Colors.grey;
    case 'blueGrey':
      return Colors.blueGrey;
  }
  return Colors.white;
}